version: '3'
services:
  app:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - ./app/.bundle/config:/usr/local/bundle/config
      - ./app:/app
      - app-vendor:/app-vendor
    entrypoint: sh
    command: -c "while true; do sleep 10; done"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
volumes:
  app-vendor:
    driver: local
